### PR TITLE
api: pass actual Header through newRPCOutput function

### PR DESCRIPTION
**Pull request by yoomee1313**
## Proposed changes

- GetTransactionByHash and RpcOutputReceipt passes null to the parameter block of newRPCTransaction. So the calculation of effectiveGasPrice couldn't work.
- This PR fixes those functions to pass actual Header.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

Test at private network which kaia hardfork has been enabled at 80
tested two transactions

tx1: EthereumDynamicFee tx of block 50 which is BEFORE kaia hardfork
tx2: EthereumDynamicFee tx of block 163 which is AFTER kaia hardfork
```
// main
> kaia.getTransaction("0x6e436476a3f29f95eebfe9e5d28f50b90185170726631c4ae07cd1a0fd260a98").gasPrice
750000000000
> eth.getTransaction("0x6e436476a3f29f95eebfe9e5d28f50b90185170726631c4ae07cd1a0fd260a98").gasPrice
25000000000
> kaia.getTransaction("0x0b964370b5af896ab70b1e4957ec4908435877b3fad6c7b13f54e86b027add93").gasPrice
750000000000
> eth.getTransaction("0x0b964370b5af896ab70b1e4957ec4908435877b3fad6c7b13f54e86b027add93").gasPrice
25000000033
```
```
// PR
> kaia.getTransaction("0x6e436476a3f29f95eebfe9e5d28f50b90185170726631c4ae07cd1a0fd260a98").gasPrice
25000000000
> eth.getTransaction("0x6e436476a3f29f95eebfe9e5d28f50b90185170726631c4ae07cd1a0fd260a98").gasPrice
25000000000
> kaia.getTransaction("0x0b964370b5af896ab70b1e4957ec4908435877b3fad6c7b13f54e86b027add93").gasPrice
25000000033
> eth.getTransaction("0x0b964370b5af896ab70b1e4957ec4908435877b3fad6c7b13f54e86b027add93").gasPrice
25000000033
>
```

### CODE REVIEW

**Review by hyeonLewis — APPROVED** [review]

**Comment by blukat29** [comment]
@yoomee1313 Please fix both `eth.getTransaction` and `kaia.getTransaction` to return the fields `maxFeePerGas` and `maxPriorityFeePerGas` if the transaction has it. I can't find those fields anywhere in our RPC.

Compare with Eth Sepolia RPC.
- See Eth API's `getTransaction(txid).{gasPrice, maxFeePerGas, maxPriorityFeePerGas}` and `getTransactionReceipt(txid).effectiveGasPrice`.
- I can confirm that in Eth, `getTransaction(txid).gasPrice == getTransactionReceipt(txid).effectiveGasPrice`.
```
ken attach https://sepolia.drpc.org
// type 0
> eth.getTransaction('0x3982e54f931dff2eadd1603113e47e22d6764b2522b2ee9cf5281f914a558811')
> eth.getTransactionReceipt('0x3982e54f931dff2eadd1603113e47e22d6764b2522b2ee9cf5281f914a558811')

// type 2
> eth.getTransaction('0x0b9a198c5ce4dcdc92681e4aaa1eb9b2fc4583c2e2758f6ded86f6784f2f9154')
> eth.getTransactionReceipt('0x0b9a198c5ce4dcdc92681e4aaa1eb9b2fc4583c2e2758f6ded86f6784f2f9154')
```

**Comment by yoomee1313** [comment]
@blukat29 I'm little confused. EthereumDynamicFee TxType of klaytn have maxFeePerGas, maxPriorityFeePerGas fields and when we call `getTransaction` on EthereumDynamicFee Tx, those fields are printed. Am I missing something?
```
> eth.getTransaction("0x00969d2fc07df2bd4fd882b77d9fb93b65243cc8bfb22a17364ab3edeeac19db")
{
  accessList: [],
  ...
  gas: 5000000,
  gasPrice: 25000000045,
  hash: "0x00969d2fc07df2bd4fd882b77d9fb93b65243cc8bfb22a17364ab3edeeac19db",
  input: "0x",
  maxFeePerGas: "0xae9f7bcc00",
  maxPriorityFeePerGas: "0x2d",
  ...
  type: "0x2",
  ...
}
```
```
> klay.getTransaction("0x00969d2fc07df2bd4fd882b77d9fb93b65243cc8bfb22a17364ab3edeeac19db")
{
  accessList: [],
  ...
  gas: 5000000,
  gasPrice: 25000000045,
  hash: "0x00969d2fc07df2bd4fd882b77d9fb93b65243cc8bfb22a17364ab3edeeac19db",
  input: "0x",
  maxFeePerGas: "0xae9f7bcc00",
  maxPriorityFeePerGas: "0x2d",
  ...
  type: "TxTypeEthereumDynamicFee",
  typeInt: 30722,
  value: 1
}
```

**Comment by blukat29** [comment]
@yoomee1313 Sorry I confused. This PR fixes the issue.

**Comment by yoomee1313** [comment]
This PR is reopen in https://github.com/kaiachain/kaia/pull/26

**Pull request closed without merging**
