### PR TITLE
[Console] New javascript console runtime

### LINKED ISSUE #2000: [Console] Javascript console has a bug and lacks syntactic features
Klaytn's javascript console lacks syntactic and functional features as well as a bug from external dependency, compared to the geth console.

### 1. Syntactic and functional lack

[Klaytn]

```
> const a = 1
(anonymous): Line 1:1 Unexpected reserved word
> async function asd() { await console.log(123); }
(anonymous): Line 1:7 Unexpected token function (and 3 more errors)

```

[Geth]

```
> const a = 1
undefined
> a
1
> async function asd() { await console.log(123); }
undefined

```

### 2. [[Extenral module bug](https://github.com/ethereum/go-ethereum/issues/14649)](https://github.com/ethereum/go-ethereum/issues/14649)

[Klaytn] - incorrect

```
> floats = [0.82, 1.22, 0.54];
[0.82, 1.22, 0.54]
> floats.sort(function (a,b) { console.log('comparing', a, b, a-b); return a-b; });
comparing 0.82 1.22 -0.4
comparing 0.54 1.22 -0.6799999999999999
[0.82, 0.54, 1.22]

```

[Geth] - expected

```
> floats = [0.82, 1.22, 0.54];
[0.82, 1.22, 0.54]
> floats.sort(function (a,b) { console.log('comparing', a, b, a-b); return a-b; });
comparing 1.22 0.82 0.4
comparing 0.54 1.22 -0.6799999999999999
comparing 0.54 0.82 -0.2799999999999999
[0.54, 0.82, 1.22]

```

**Describe the solution you'd like**
Geth replaced the JS runtime `otto` to `goja`. Following this patch would work.

### PR DESCRIPTION
**Pull request by hyunsooda**
## Proposed changes

Ported from https://github.com/ethereum/go-ethereum/pull/20470.

This PR resolves #2000.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by ian0371 — APPROVED** [review]
Experimentally tested and confirmed that the issue has been solved.

**Review by ian0371 — DISMISSED** [review]
Experimentally tested and confirmed that the issue has been solved.

**Comment by blukat29** [comment]
Tested that the runtime is ES6 and existing functions are intact.

<details>
<summary>Details</summary>

- ES6 (JS2015) features (https://www.w3schools.com/js/js_es6.asp)
  - Just checking that the runtime is ES6. Not testing full features.
  - let, const keyword
	```
	> const x = 1; let y = 2;
	undefined
	> x + y
	3
	```
  - Arrow functions
    ```
    > const f = (x, y) => x*y;
	undefined
	> f(2,3)
	6
    ```
- Injected variables
  - console
    ```
    > console.log(123); console.error(456);
     123
	 456
    ```
  - bignumber.js (https://mikemcl.github.io/bignumber.js/)
	```
	> var b = new BigNumber("100")
	undefined
	> b.plus(23)
	123
	```
  - Web3
	```
	> Web3
	function Web3(provider)
	> web3.currentProvider
	{
	  send: function github.com/klaytn/klaytn/console/jsre.MakeCallback.func1(),
	  sendAsync: function github.com/klaytn/klaytn/console/jsre.MakeCallback.func1()
	}
	```
  - RPCs
    ```
	> admin.datadir
	"/home/ubuntu/klaytn/data"
	> admin.sleep(1)
	true
	> debug.isPProfRunning()
	false
	> eth.blockNumber
	136624296
	> klay.blockNumber
	136624299
	> net.networkID
	1001
	> personal.listAccounts
	[]
	> rpc.modules
	{
	  admin: "1.0",
	  debug: "1.0",
	  eth: "1.0",
	  klay: "1.0",
	  net: "1.0",
	  personal: "1.0",
	  rpc: "1.0",
	  web3: "1.0"
	}
    ```
  - loadScript
	```
	> loadScript("hello.js")
	 hello from loaded script
	```
  - inspect
	```
	> console.log({ x: 1 })
	 [object Object]
	> inspect({ x: 1 })
	{
	  x: 1
	}
	```
  - Timer
	```
	> setTimeout(() => console.log(1), 1000)
	{}
	>  1

	> var t = setInterval(() => console.log(2), 1000)
	undefined
	>  2
	 2
	 2
	> clearInterval(t)
	undefined
	```
- Autocomplete
	```
	> eth.<TAB><TAB>
	eth._requestManager            eth.getBlockNumber             eth.getTransactionReceipt
	eth.accounts                   eth.getBlockTransactionCount   eth.getUncle
	eth.blockNumber                eth.getBlockUncleCount         eth.getWork
	eth.call                       eth.getCode                    eth.hashrate
	```


</details>

**Review by blukat29 — DISMISSED** [review]

**Comment by yoomee1313** [comment]
It seems that you need to resolve the conflict one more time. Could you resolve the conflict?

**Comment by blukat29** [comment]
Resolved on GitHub. PTAL.

**Comment by hyunsooda** [comment]
LGMT. Thank you

**Review by blukat29 — APPROVED** [review]

**Review by yoomee1313 — APPROVED** [review]

**Pull request merged**
