### PR TITLE
[SC] Enable chaindatafetcher option available at ksen

### PR DESCRIPTION
**Pull request by hqjang-pepper**
## Proposed changes

related Issue : https://github.com/klaytn/klaytn/issues/1341

- tested under local environment, scn+spn+sen setting with `--chaindatafetcher` option.
- I checked blockgroup and tracegroup data stream well to kafka broker with no problem.
## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hyunsooda** [comment]
@hqjang-pepper, Okay it works. Those variables may be populated to another array. It would remove lengthy copy and paste. 

@jeongkyun-oh, This feature seemed initially intended for `EN` only. Do you have some insight or advice about the operation's side-effect or performance issues if the CN node uses this feature?

**Comment by jeongkyun-oh** [comment]
@hyunsooda the feature is added to only ENs for KAS at that time. I think it should work for CNs and PNs including service chain. Live data streaming will be operated during the tx processing, so I think it has little effect on performance. 

However, data extraction for the past data (ususally for data reloading to kafka due to data corruption, or data missing) takes more resources since it fetches the data from database (if it is not cached) and reprocess txs inefficiently. So, it has more effect on the performance and it may be quite critical. It would be better to use this feature from only (S)ENs.

@hqjang-pepper Could you please attach the test result as well as the chaindatafetcher configuration?

**Comment by hqjang-pepper** [comment]
With only basic options set so that the chaindata fetcher can use kafka, I checked whether the data was loaded into the kafka topic.
- option I gave at .conf file
`ADDITIONAL="--chaindatafetcher --chaindatafetcher.mode kafka --chaindatafetcher.kafka.brokers localhost:9092"`

- check kafka topic data
```
(...omitted, same format as follows)
{"blockNumber":417436,"result":{"blockscore":"0x1","committee":["0x29d231d1cab42bfbfa592dff4d4ea1d8c73da91e"],"extraData":"0xda83010803846b6c617989676f312e31352e31338664617277696e0000000000f89ed59429d231d1cab42bfbfa592dff4d4ea1d8c73da91eb841d4d734647143bf958abb1a1a0fa43396187d02a4dfccf3f501ae6f0a8def62602fd5501d9485b6eb7240866e0614884d31f14a6ed7f01bbd141be27a6f1f811601f843b8415fa7c4491af32cb2a0d3e2b496d17cc1091bcfaaf34b5d049c77d719174bd0f63b3e13b97dfec8107a389bcb5c5dfe04b90c40ae066cfc1f83e07926cbbaee8a01","gasUsed":"0x0","governanceData":"0x","hash":"0xb30b42da70301f85faf264d78bb9fdcfaa3f1bf0ce8ef45257b4da6deaf5b0cc","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","number":"0x65e9c","parentHash":"0xd36aebd1090b44ed6acadf2f2cd2e0884c12f9ffccca06284b2044c71a964a43","proposer":"0x29d231d1cab42bfbfa592dff4d4ea1d8c73da91e","receiptsRoot":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","reward":"0x0000000000000000000000000000000000000000","size":"0x273","stateRoot":"0x0cba6c89304453683826da5c505fb3491f0ac1d8208ea70830b3a8ffdc9a35f4","timestamp":"0x6262582d","timestampFoS":"0x0","totalBlockScore":"0x65e9d","transactions":[],"transactionsRoot":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470","voteData":"0x"}}
^CProcessed a total of 1885 messages
```


Because data streaming started when the chaindata fetcher option was turned on, I couldn't find data extraction for the past data as @jeongkyun-oh said. 
Do I have to conduct another test?

**Comment by hyunsooda** [comment]
@hqjang-pepper, I meant you can use dotdotdot operator by declaring the array variable that contains those options. The go-compiler seems not to support this operation at compile time since the array length is always not deterministic at compile time. Anyway, I think we need a wrapper for the flag initialization. Let this work hold be off to next time.  

@hqjang-pepper, @jeongkyun-oh,  I think his word, `past data` seems to the blocks which are far behind the current block number. I experienced that the memory was rapidly increased when the `sen` node fetches blocks to sync. This performance overhead in `sen` is not my concern since it does not harm the consensus work. The other `sen` nodes can continuouslly propagate txs instead of busy `sen`s. So, the feature must not harm the performance of essential behaviors the `scn` has when `scn`s turn on its feature. Moreover, the `scn` has another work compared with the origin `CN` for value transfer requests and handling through a dedicated RPC line with mainbridge node.

**Comment by jeongkyun-oh** [comment]
@hqjang-pepper It would be nicer to have simple test for `trace` data as well (it needs to add `--vm.internaltx`). I think just do the same test after some blocks were produced which triggers fetching data for old blocks. I think this is enough to add those flags. I don't have any other concerns at the moment.

@hyunsooda 
> when scns turn on its feature
You meant `sen`s right?
Adding those flags is probably good for testing purpose since the `sen` cannot generate a block. But, I recommend not to turn on the feature from SCN for production.

**Comment by hyunsooda** [comment]
@jeongkyun-oh, `scn` is right, but you caught my concern. The performance overhead must not harm block generation (execute tx, consensus, etc). Then, what's better between removing this feature in `scn` or leaving it to decide by the ServiceChain operator?

**Comment by jeongkyun-oh** [comment]
@hyunsooda I think latter one is better. We may need to let them know the caution of using chaindatafetcher on SCNs.

**Comment by hyunsooda** [comment]
@jeongkyun-oh, Okay, thanks for the advice.
@hqjang-pepper, Okay, make sense.

**Review by hyunsooda — APPROVED** [review]

**Comment by hqjang-pepper** [comment]
Sorry for late response. I did another tests about chaindata fetcher.
When SCN directly make transaction, problem occurs when it tries to make BlockGroup Output. 
It seems that some wrong parameter was passed to  `klaytnApi.RpcOutputReceipt`. 

```
panic: runtime error: index out of range [0] with length 0

goroutine 1097 [running]:
github.com/klaytn/klaytn/datasync/chaindatafetcher/kafka.makeBlockGroupOutput(0xc000247000, 0xc016ae0150, 0x0, 0x0, 0x0, 0x0)
        /Users/janghyeong-gyu/workspace/klaytn-development/SCchaindatafetcher/klaytn/datasync/chaindatafetcher/kafka/utils.go:81 +0x71f
github.com/klaytn/klaytn/datasync/chaindatafetcher/kafka.(*repository).HandleChainEvent(0xc01960e360, 0xc016ae0150, 0xf9beb1567e2375e9, 0xe94ad7b84f91fcc8, 0x4a0b3357ee1fe9bc, 0x959b11fdfad13cf2, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/janghyeong-gyu/workspace/klaytn-development/SCchaindatafetcher/klaytn/datasync/chaindatafetcher/kafka/repository.go:75 +0x517
github.com/klaytn/klaytn/datasync/chaindatafetcher.(*ChainDataFetcher).retryFunc.func1(0xc016ae0150, 0xf9beb1567e2375e9, 0xe94ad7b84f91fcc8, 0x4a0b3357ee1fe9bc, 0x959b11fdfad13cf2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/janghyeong-gyu/workspace/klaytn-development/SCchaindatafetcher/klaytn/datasync/chaindatafetcher/chaindata_fetcher.go:533 +0x85
github.com/klaytn/klaytn/datasync/chaindatafetcher.(*ChainDataFetcher).updateInsertionTimeGauge.func1(0xc016ae0150, 0xf9beb1567e2375e9, 0xe94ad7b84f91fcc8, 0x4a0b3357ee1fe9bc, 0x959b11fdfad13cf2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/janghyeong-gyu/workspace/klaytn-development/SCchaindatafetcher/klaytn/datasync/chaindatafetcher/chaindata_fetcher.go:500 +0xb0
github.com/klaytn/klaytn/datasync/chaindatafetcher.(*ChainDataFetcher).handleRequestByType(0xc000180e00, 0x30, 0x1, 0xc016ae0150, 0xf9beb1567e2375e9, 0xe94ad7b84f91fcc8, 0x4a0b3357ee1fe9bc, 0x959b11fdfad13cf2, 0x0, 0x0, ...)
        /Users/janghyeong-gyu/workspace/klaytn-development/SCchaindatafetcher/klaytn/datasync/chaindatafetcher/chaindata_fetcher.go:369 +0x165
github.com/klaytn/klaytn/datasync/chaindatafetcher.(*ChainDataFetcher).handleRequest(0xc000180e00)
        /Users/janghyeong-gyu/workspace/klaytn-development/SCchaindatafetcher/klaytn/datasync/chaindatafetcher/chaindata_fetcher.go:427 +0x55c
created by github.com/klaytn/klaytn/datasync/chaindatafetcher.(*ChainDataFetcher).Start
        /Users/janghyeong-gyu/workspace/klaytn-development/SCchaindatafetcher/klaytn/datasync/chaindatafetcher/chaindata_fetcher.go:162 +0x47

```

**Review by jeongkyun-oh — APPROVED** [review]

**Comment by hqjang-pepper** [comment]
Decided to apply this option only at `ksen`.
@hyunsooda review again please. Thanks

**Comment by hyunsooda** [comment]
SGTM

**Review by hyunsooda — APPROVED** [review]

**Review by 2dvorak — APPROVED** [review]
LGTM

**Pull request merged**
