### PR TITLE
Faster trie node encoding

### PR DESCRIPTION
**Pull request by hqjang-pepper**
## Proposed changes

- This PR supports rlp encoding of nested trie node interfaces.
- Obviously getting type and reflect package is expensive, so we can do it in compile level.
- Use new encodebuffer at `hasher` and `stackTrie`
- should be merged after #1659 
- related ethereum PR : https://github.com/ethereum/go-ethereum/pull/24126

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hqjang-pepper** [comment]
Benchmark test result
Before : dev branch
after : applying #1659 + #1656 + #1679

```
before
BenchmarkHashFixedSize
BenchmarkHashFixedSize/10
BenchmarkHashFixedSize/10-10 	           27930	     42784 ns/op	   14004 B/op	     157 allocs/op
BenchmarkHashFixedSize/100
BenchmarkHashFixedSize/100-10         	   10000	    100930 ns/op	   65665 B/op	     777 allocs/op
BenchmarkHashFixedSize/1K
BenchmarkHashFixedSize/1K-10          	    1232	    982107 ns/op	  657792 B/op	    7784 allocs/op
BenchmarkHashFixedSize/10K
BenchmarkHashFixedSize/10K-10         	     277	   4412435 ns/op	 6906100 B/op	   79662 allocs/op
BenchmarkHashFixedSize/100K
BenchmarkHashFixedSize/100K-10        	      30	  40766426 ns/op	68241484 B/op	  794507 allocs/op

after
BenchmarkHashFixedSize
BenchmarkHashFixedSize/10
BenchmarkHashFixedSize/10-10 	           60531	     19774 ns/op	   10030 B/op	     142 allocs/op
BenchmarkHashFixedSize/100
BenchmarkHashFixedSize/100-10         	   16846	     71875 ns/op	   49463 B/op	     708 allocs/op
BenchmarkHashFixedSize/1K
BenchmarkHashFixedSize/1K-10          	    1630	    732230 ns/op	  500323 B/op	    7099 allocs/op
BenchmarkHashFixedSize/10K
BenchmarkHashFixedSize/10K-10         	     402	   2987934 ns/op	 5238605 B/op	   73313 allocs/op
BenchmarkHashFixedSize/100K
BenchmarkHashFixedSize/100K-10        	      44	  27326826 ns/op	51688571 B/op	  730456 allocs/op
```

**Comment by hqjang-pepper** [comment]
- hash
  - operation : 48 ~ 26% faster
  - alloc : 5% less
- commit
  - operation : 20~50% faster
  - alloc: 10% less

**Comment by hqjang-pepper** [comment]
DeriveShaOrig benchmark Test - using stackTrie
before : v 1.9.1
after : applying https://github.com/klaytn/klaytn/pull/1659 + https://github.com/klaytn/klaytn/pull/1656 + https://github.com/klaytn/klaytn/pull/1679 + https://github.com/klaytn/klaytn/pull/1648 (optimize derivesha)

```
Before this PR : 
BenchmarkDeriveShaOrig/100test-stackTrie-10         	    7977	    148040 ns/op
BenchmarkDeriveShaOrig/1000test-stackTrie-10         	     744	   1533285 ns/op
BenchmarkDeriveShaOrig/4000test-stackTrie-10         	     194	   5926051 ns/op


After this PR :
BenchmarkDeriveShaOrig/100test-stackTrie-10         	    9498	    121794 ns/op
BenchmarkDeriveShaOrig/1000test-stackTrie-10         	     968	   1234340 ns/op
BenchmarkDeriveShaOrig/4000test-stackTrie-10         	     243	   4800326 ns/op
```

comparing with other deriveSha implementation
```
BenchmarkDeriveSha
BenchmarkDeriveSha/Concat,4000
BenchmarkDeriveSha/Concat,4000-10         	     375	   3036499 ns/op
BenchmarkDeriveSha/Orig,4000
BenchmarkDeriveSha/Orig,4000-10           	     238	   4893403 ns/op
BenchmarkDeriveSha/Simple,4000
BenchmarkDeriveSha/Simple,4000-10         	     207	   5601969 ns/op

BenchmarkDeriveShaSingleAccount/Concat
BenchmarkDeriveShaSingleAccount/Concat-10         	     385	   3032999 ns/op
BenchmarkDeriveShaSingleAccount/Orig
BenchmarkDeriveShaSingleAccount/Orig-10           	     238	   5134026 ns/op
BenchmarkDeriveShaSingleAccount/Simple
BenchmarkDeriveShaSingleAccount/Simple-10         	     193	   6258522 ns/op
```

**Comment by blukat29** [comment]
Replaced by https://github.com/klaytn/klaytn/pull/1974.

**Pull request closed without merging**
