### PR TITLE
Added from/to fields to trace result + Added an empty slice of InternalCallTrace

### PR DESCRIPTION
**Pull request by jeongkyun-oh**
## Proposed changes

- Fixed comparision logic for InternalTrace instead of using `reflect.DeepEqual`.
  - `reflect.DeepEqual` does return `false` for comparison empty slice with `nil` value.
- The `from` and `to` fields are missing to be added. So, they are added.

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ehnuje** [comment]
> - Fixed comparision logic for InternalTrace instead of using reflect.DeepEqual.
> - Added From / To Fields to trace result.

@jeongkyun-oh Please specify the reason of the changes.

**Comment by jeongkyun-oh** [comment]
> > * Fixed comparision logic for InternalTrace instead of using reflect.DeepEqual.
> > * Added From / To Fields to trace result.
> 
> @jeongkyun-oh Please specify the reason of the changes.

The reason is that reflect.DeepEqual does return false for comparison empty slice with nil value

**Comment by aidan-kwon** [comment]
@jeongkyun-oh Can you add a test case for this PR?

**Comment by ehnuje** [comment]
Please check this link
https://play.golang.org/p/nbFFo6-q8uB

**Comment by ehnuje** [comment]
> Repository traces implementation fix

This title is vague, could you please change it to the one with more specific meaning?

**Comment by jeongkyun-oh** [comment]
@ehnuje @aidan-kwon @KimKyungup PTAL.

**Pull request merged**
