### PR TITLE
Updated log levels for downloader

### PR DESCRIPTION
**Pull request by jeongkyun-oh**
## Proposed changes

- Although the unwanted data packets are received from the remote peers, it is hard to know.
- This PR updates some `DEBUG` log levels to `WARN` for unmatched request/retrieval.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by yoomee1313 — APPROVED** [review]

**Review by winnie-byun — APPROVED** [review]
Does this happen often?

**Comment by jeongkyun-oh** [comment]
@winnie-byun Not really. Only it leaves logs when the response headers are not matched with the requested ones.

**Review by aidan-kwon — COMMENTED** [review]
I don't agree to raise the logs level. The logs are printed when other peers, not the node printing logs, malfunctioned. The node doesn't need to be warned by the message that doesn't affect the node. Indeed, other nodes could dirty their peer's log intentionally if this change is merged.

**Review by KimKyungup — COMMENTED** [review]
I think same with @aidan-kwon.

**Comment by jeongkyun-oh** [comment]
@aidan-kwon @KimKyungup I understand the point. Let me close this PR.

**Pull request closed without merging**
