### PR TITLE
[SC] Removed unused code

### PR DESCRIPTION
**Pull request by hyunsooda**
## Proposed changes

I was reading Service Chain (SC) codebase to build up base knowledge for understanding internal behavior. This PR removes unnecessary (unused) code from ``` func (pool *BridgeTxPool) addTx(tx *types.Transaction) error ```. I found entire code scheme for SC seems similar to CN logic, but compact code blocks were brought from there. 

In my first view, the author of SC's entire scheme might have been a mistake when he pulled code blocks from CN logic. I think ```addTxs``` function in SC seemed to pull from https://github.com/klaytn/klaytn/blob/dev/blockchain/tx_pool.go#L1199.
 
One more thing, there is a lack of features like transaction validation before inserting tx to txpool, where supported in CN logic. I don't know the authors' intention whether this compact version (lack of feature compared with CN) is intended or should be improved from now on.

I would appreciate it if some experiencer advise. Thanks a lot.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by aidan-kwon** [comment]
Thank you for your contribution. 
I like your suggestion validating transactions in `BridgeTxPool`. Although the current code doesn't make a security issue because transactions in `BridgeTxPool` are finally sent to `TxPool` (CN logic you remarked) and validated, we can consider pre-validation in `BridgeTxPool`. I think we cannot adopt all validation logic in CN because a bridge doesn't know the balance and nonce information of another chain, but some type of checking logic can be adopted such as format check. 
BTW, we are having QA period for v1.8.0 now. Your PR could be reviews and merged after v1.8.0 release targetting 16th March.

**Comment by hyunsooda** [comment]
Hi @aidan-kwon,

No security issue was found in my view too, with limited knowledge for now. Thanks for your comment. I'll consider which functions should be added.

**Comment by hqjang-pepper** [comment]
Your code seems failed at some tests.
Have you checked?

**Comment by hyunsooda** [comment]
Hi @hqjang-pepper, 

This commit does not touch origin behavior but also does not remove it. It just removes dead code. I did re-run CircleCI and is now passed. The error seemed to occur in another context that has no relation.

**Review by KimKyungup — APPROVED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Comment by aidan-kwon** [comment]
@jeongkyun-oh Could you review this?

**Review by jeongkyun-oh — APPROVED** [review]

**Review by hqjang-pepper — APPROVED** [review]

**Pull request merged**
