### PR TITLE
[Master] release/v1.5.3 QA Sign-off

### PR DESCRIPTION
**Pull request by circleci-klaytn**
This PR is automatically created by CI to release a new official version of klaytn.

When this PR is approved by QA team, a new version will be released.

### CODE REVIEW

**Comment by circleci-klaytn** [comment]
<details><summary>Builds ready [4b49582]</summary><ul><li>Linux: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kcn-v1.5.3~rc.1-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kpn-v1.5.3~rc.1-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/ken-v1.5.3~rc.1-0-linux-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kscn-v1.5.3~rc.1-0-linux-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kspn-v1.5.3~rc.1-0-linux-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/ksen-v1.5.3~rc.1-0-linux-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kbn-v1.5.3~rc.1-0-linux-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kgen-v1.5.3~rc.1-0-linux-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/homi-v1.5.3~rc.1-0-linux-amd64.tar.gz>homi</a> </li><li>Darwin: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kcn-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kpn-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/ken-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kscn-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kspn-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/ksen-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kbn-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kgen-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/homi-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>homi</a> </li><li>Baobab-linux: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kcn-baobab-v1.5.3~rc.1-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kpn-baobab-v1.5.3~rc.1-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/ken-baobab-v1.5.3~rc.1-0-linux-amd64.tar.gz>ken</a> </li><li>Baobab-darwin: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kcn-baobab-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/kpn-baobab-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.1/ken-baobab-v1.5.3~rc.1-0-darwin-10.10-amd64.tar.gz>ken</a> </li></ul></details>

**Review by aidan-kwon — DISMISSED** [review]

**Review by ehnuje — DISMISSED** [review]

**Review by yoomee1313 — DISMISSED** [review]

**Comment by winnie-byun** [comment]
We should add [PR#706](https://github.com/klaytn/klaytn/pull/706) to pass the coverage test.

**Comment by circleci-klaytn** [comment]
<details><summary>Builds ready [eaf00b0]</summary><ul><li>Linux: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kcn-v1.5.3~rc.2-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kpn-v1.5.3~rc.2-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/ken-v1.5.3~rc.2-0-linux-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kscn-v1.5.3~rc.2-0-linux-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kspn-v1.5.3~rc.2-0-linux-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/ksen-v1.5.3~rc.2-0-linux-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kbn-v1.5.3~rc.2-0-linux-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kgen-v1.5.3~rc.2-0-linux-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/homi-v1.5.3~rc.2-0-linux-amd64.tar.gz>homi</a> </li><li>Darwin: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kcn-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kpn-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/ken-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kscn-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kspn-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/ksen-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kbn-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kgen-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/homi-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>homi</a> </li><li>Baobab-linux: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kcn-baobab-v1.5.3~rc.2-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kpn-baobab-v1.5.3~rc.2-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/ken-baobab-v1.5.3~rc.2-0-linux-amd64.tar.gz>ken</a> </li><li>Baobab-darwin: <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kcn-baobab-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/kpn-baobab-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.5.3~rc.2/ken-baobab-v1.5.3~rc.2-0-darwin-10.10-amd64.tar.gz>ken</a> </li></ul></details>

**Comment by KimKyungup** [comment]
# v1.5.3 Release Notes

**Comment by KimKyungup** [comment]
# Tests

**Comment by aidan-kwon** [comment]
Rolling update test (v1.5.2 -> release/v1.5.3) `passed`

**Review by winnie-byun — APPROVED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Review by jeongkyun-oh — APPROVED** [review]

**Pull request merged**
