### PR TITLE
Increase the required go version to 1.20

### PR DESCRIPTION
**Pull request by hyunsooda**
## Proposed changes

By the change of #2032, the minimal Golang version should be >1.19. (`Atomic.Bool` was introduced in 1.19)

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by yoomee1313** [comment]
Thank you, @hyunsooda. Do we have to update to 1.20? If it's caused by atomic.Bool, then what about go1.19?

**Review by blukat29 — APPROVED** [review]
@yoomee1313 Because go1.19 is now deprecated, it should be reasonable to require 1.20 or higher. Ref. https://endoflife.date/go "Each major Go release is supported until there are two newer major releases."

**Review by yoomee1313 — APPROVED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Comment by aidan-kwon** [comment]
We can also consider go1.21 including security fixes of `cyprto/tls`, `net/http`, and others. https://go.dev/doc/devel/release#go1.21.0
Go evolves too fast

**Comment by blukat29** [comment]
@aidan-kwon Let's update once again when go1.22 is out

**Pull request merged**
