### PR TITLE
Fixed SetComponents method

### PR DESCRIPTION
**Pull request by jeongkyun-oh**
## Proposed changes

- Fixed SetComponent method to set blockchainAPI correctly.

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by aidan-kwon — APPROVED** [review]

**Review by KimKyungup — APPROVED** [review]

**Comment by jeongkyun-oh** [comment]
@ehnuje @yoomee1313 @winnie-byun Please take a look.

**Review by ehnuje — APPROVED** [review]

**Comment by ehnuje** [comment]
@jeongkyun-oh Can this be tested?

**Comment by jeongkyun-oh** [comment]
@ehnuje Yes. I tested it manually.

**Comment by ehnuje** [comment]
@jeongkyun-oh Oh, I mean an unit test can be made for this. Which should be failed without this PR.

**Review by winnie-byun — APPROVED** [review]

**Review by yoomee1313 — APPROVED** [review]

**Comment by jeongkyun-oh** [comment]
@ehnuje I think it can, but making several mocks is a bit more work. I will add them in another PR.

**Pull request merged**
