### PR TITLE
blockchain/asm: assembly parser label fixes

### PR DESCRIPTION
**Pull request by ehnuje**
## Proposed changes

- This PR is derived from https://github.com/ethereum/go-ethereum/pull/20210
- Also, to be aligned with go-ethereum, https://github.com/ethereum/go-ethereum/pull/18058 is added

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by yoomee1313 — APPROVED** [review]

**Comment by aidan-kwon** [comment]
Can this change make any incompatibility in Cypress?

**Review by aidan-kwon — APPROVED** [review]
I think this change is okay. However, we should check the incompatibility the change may cause.

**Comment by ehnuje** [comment]
@aidan-kwon How can we check the possibility of incompatibility in Cypress? Sync the node from the genesis?

**Comment by aidan-kwon** [comment]
> @aidan-kwon How can we check the possibility of incompatibility in Cypress? Sync the node from the genesis?

@ehnuje It seems that `compiler` doesn't affect generating a block, but I just want to make sure it really doesn't since I don't fully understand where `compiler` in `asm` package is used. How do you think about it? If you think the change is safe, we don't need to test. If not, we need to find testing methods.

**Review by jeongkyun-oh — APPROVED** [review]

**Review by KimKyungup — APPROVED** [review]
For now, Klaytn doesn't use this code.
Geth has `evm` cmd using this code. But it is not included makefile.
Anyway, let's merge this.

**Pull request merged**
