### PR TITLE
Migrate to `go mod` & resolve `urfave/cli` problem

### PR DESCRIPTION
**Pull request by frostornge**
## Proposed changes
- Migrate to `go module` from `dep` (#84)
    - Remove all `build/env.sh` command from makefile
    - Fix dependency version mismatch errors (described in #153)
    - Vendor dependencies by `go mod vendor` & Add `-mod=vendor` options in makefile
- Resolve `urfave/cli` problem
    - Unify dependencies...
    - `gopkg.in/urfave/cli.v1` to `github.com/urfave/cli@1.21.0`
- Migrate to golangci/golangci-linter. because it's faster than gometalinter and it is deprecated.
    - `gometalinter` cause errors by fetching deprecated package url `github.com/nicksnyder/go-i18n/i18n`

## Types of changes

Please put an x in the boxes related to your change.

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Related issues
- #84 
- #153 

## Further comments
It's quiet simple solutions for migrate dep to module.
But i don't have enough time to develop this... So if CI keeps failing, please fix errors :)

### CODE REVIEW

**Comment by frostornge** [comment]
Retry :)

**Comment by jeonghonah** [comment]
To reflect and build this patch, the actions below are explicitly required. I don't think it's clear why this PR should be reflected currently.

1. export GO111MODULE=on
2. go mod vendor

**Comment by frostornge** [comment]
> To reflect and build this patch, the actions below are explicitly required. I don't think it's clear why this PR should be reflected currently.
> 
> 1. export GO111MODULE=on (if working on $GOPATH/src)
> 2. go mod vendor

1. How about adding `export GO111MODULE=on` in Makefile?
2. I think running `go mod vendor` is unnecessary action. and i'll update it later.

**Comment by jeonghonah** [comment]
@frostornge I agree with your opinion. Can you also check that version of packages in vendor? It would be nice to have the same version as the previous one.

**Comment by KimKyungup** [comment]
@frostornge I think if `make all` can compile our code after cloning this code, it's ok.
But if 1st or every `make all` takes too much time for go mod vender, including the vendor code in our git is better than removing all vender code.

**Comment by jeonghonah** [comment]
@frostornge Do you have any progress? It will be nice if the issue is solved before October. If it is difficult to correct in near future, please note that I am planning to make another fix.

**Pull request closed without merging**
