### PR TITLE
Increase redis timeout durations and change a log level

### PR DESCRIPTION
**Pull request by aidan-kwon**
## Proposed changes

- Increase redis timeout durations
  - Ping takes 10 ~ 20 ms from my office to EC2 in the best network condition. I think it could take longer than 100 ms easily depends on network congestion. 
- Change a log level

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [x] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by KimKyungup** [comment]
If redis server is down, Can this timeout make big delay during block processing?

**Comment by aidan-kwon** [comment]
> If redis server is down, Can this timeout make big delay during block processing?

1. It doesn't need to be considered with this change. As you know, Klaytn could request more than thousands of times to trieNodeCache in a second. Increasing timeout duration by three times doesn't a big deal in the circumstance you mentioned. It should be handled in another context. 
2. (Only for KES) KES doesn't work properly if redis failed since KES service nodes cannot subscribe latest block number.

**Comment by KimKyungup** [comment]
> > If redis server is down, Can this timeout make big delay during block processing?
> 
> 1. It doesn't need to be considered with this change. As you know, Klaytn could request more than thousands of times to trieNodeCache in a second. Increasing timeout duration by three times doesn't a big deal in the circumstance you mentioned. It should be handled in another context.
> 2. (Only for KES) KES doesn't work properly if redis failed since KES service nodes cannot subscribe latest block number.

I forgot that we use redis pub/sub. Thanks. :)

**Review by KimKyungup — APPROVED** [review]

**Review by yoomee1313 — DISMISSED** [review]

**Comment by winnie-byun** [comment]
The new timeout will can slow down the fetcher node. It is meaningless to run a fetcher node that is slow. How about making it as a new go routine for redis set?

**Review by jeongkyun-oh — APPROVED** [review]

**Comment by KimKyungup** [comment]
> The new timeout will can slow down the fetcher node. It is meaningless to run a fetcher node that is slow. How about making it as a new go routine for redis set?

I think we can make another PR to apply a new goroutine to set. :)

**Comment by aidan-kwon** [comment]
> The new timeout will can slow down the fetcher node. It is meaningless to run a fetcher node that is slow. How about making it as a new go routine for redis set?

@winnie-byun I separated the timeout to read/write timeouts. The write timeout is kept with old values for a fetcher node. I will consider making a go routine for redis later.

**Review by KimKyungup — DISMISSED** [review]

**Comment by ehnuje** [comment]
@aidan-kwon TestNewRedisCache_Timeout failed, could you please check?
```
--- FAIL: TestNewRedisCache_Timeout (0.90s)
    cache_redis_test.go:155: 
        	Error Trace:	cache_redis_test.go:155
        	Error:      	Not equal: 
        	            	expected: 100ms
        	            	actual  : 300ms
        	Test:       	TestNewRedisCache_Timeout
```

**Comment by aidan-kwon** [comment]
Reviewers, I increased Redis timeout larger than the first suggestion applying async Redis set in https://github.com/klaytn/klaytn/pull/819. I hope that these changes get rid of some reviewers' worries about slowing KES fetcher nodes.

**Review by winnie-byun — APPROVED** [review]

**Review by yoomee1313 — APPROVED** [review]

**Review by jeongkyun-oh — APPROVED** [review]

**Review by KimKyungup — APPROVED** [review]

**Review by ehnuje — APPROVED** [review]

**Pull request merged**
