### PR TITLE
Change go dep to go module

### PR DESCRIPTION
**Pull request by jeonghonah**
## Proposed changes

- This PR changes go dep to go module which is described at #84 and #166.
- Sufficient testing is required since packages in vendor has been updated to a newer version that is compatible.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- #84, #166

## Further comments

- This PR also passed an error case in #211 which uses klaytn as external package. It might be related to the following issues:
    - #153, #277
- Tested go version: go1.13.1 darwin/amd64

### CODE REVIEW

**Comment by ehnuje** [comment]
@jeonghonah What kind of testing do you think needed to ensure the change is valid? If you have some in your mind, it would be helpful if you share them.

**Comment by jeonghonah** [comment]
@ehnuje I think testing for the release of v1.3.0 will be enough.

**Comment by ehnuje** [comment]
@jeonghonah If so, will we test this PR on v1.3.0? I think we'd better to merge this PR ASAP and then test this indirectly before v.1.3.0 How do you think @kjhman21

**Comment by jeonghonah** [comment]
@KimKyungup This PR generates a different binary. The minor version of some packages are updated by go module. FYI, go1.13.1 is used for this PR.

**Comment by kjhman21** [comment]
@jeonghonah I agree @ehnuje's opinion. @laggu is making a QA test tool. Once it's done, we can easily test this PR.

At lease we need to check:
1. It can validate the latest block from the first block for Baobab and Cypress
2. Performance differences
3. Stability test with various test cases for some duration

**Comment by jeonghonah** [comment]
@kjhman21 Please approve this PR.

**Pull request merged**
