### PR TITLE
rpc: replace big.Int to hexutil.Big for RPC handling

### PR DESCRIPTION
**Pull request by yoomee1313**
## Proposed changes
- This PR is derived from [geth PR #16942](https://github.com/ethereum/go-ethereum/pull/16942).
- The replacement job is done before, but some codes are remained unchanged.
- klay_getBalance, klay_blockNumber, klay_gasPriceAt, klay_gasPrice, klay_chainID are the unchanged apis.
- The RPC result is same as dev branch, so no document revision is needed.
Below is the result of rpc call of dev branch and this PR branch. You can see the result is not changed.

dev Branch
```
> klay_getBalance
{"jsonrpc":"2.0","id":73,"result":"0x446c3b15f9926687d2c40534fdb564000000000000"}

> klay_blockNumber
{"jsonrpc":"2.0","id":73,"result":"0x1f9a"}

> klay_gasPriceAt
{"jsonrpc":"2.0","id":73,"result":"0xee6b280"}
{"jsonrpc":"2.0","id":73,"error":{"code":-32000,"message":"Unknown block"}}

> klay_gasPrice
{"jsonrpc":"2.0","id":73,"result":"0xee6b280"} // test network's gasPrice is 250000000

> klay_chainID
{"jsonrpc":"2.0","id":73,"result":"0xe5a51"} // test network's chainID is 940625
```
this PR
```
klay_getBalance
{"jsonrpc":"2.0","id":73,"result":"0x446c3b15f9926687d2c40534fdb564000000000000"}

klay_blockNumber
{"jsonrpc":"2.0","id":73,"result":"0x1f9a"}

klay_gasPriceAt
{"jsonrpc":"2.0","id":73,"result":"0xee6b280"}
{"jsonrpc":"2.0","id":73,"error":{"code":-32000,"message":"Unknown block"}}

klay_gasPrice
{"jsonrpc":"2.0","id":73,"result":"0xee6b280"} // test network's gasPrice is 250000000

klay_chainID
{"jsonrpc":"2.0","id":73,"result":"0xe5a51"} // test network's chainID is 940625
```
## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [x] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by KimKyungup** [comment]
@yoomee1313 Why are some codes remained unchanged?

**Review by aidan-kwon — DISMISSED** [review]
It would be better if you attach your test results ensuring API result is the same with old version.

**Comment by yoomee1313** [comment]
> @yoomee1313 Why are some codes remained unchanged?
Geth forgotten to change when changing old data structures to hexutil.

> It would be better if you attach your test results ensuring API result is the same with old version.
I updated this PR's description!

**Review by ehnuje — APPROVED** [review]

**Review by jeongkyun-oh — DISMISSED** [review]

**Comment by KimKyungup** [comment]
> > It would be better if you attach your test results ensuring API result is the same with old version.
> 
> I updated this PR's description!

@yoomee1313 Do all apis return same result with old one?? :)

**Review by KimKyungup — DISMISSED** [review]

**Comment by KimKyungup** [comment]
@yoomee1313 Rebase please.

**Comment by yoomee1313** [comment]
> @yoomee1313 Rebase please.

@KimKyungup Resolved the conflict!

**Review by ehnuje — APPROVED** [review]

**Review by KimKyungup — APPROVED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Review by winnie-byun — APPROVED** [review]

**Review by jeongkyun-oh — APPROVED** [review]

**Pull request merged**
