### PR TITLE
Fix sender address check

### PR DESCRIPTION
**Pull request by kjhman21**
## Proposed changes

- fix the address that is used in the mainnet in AddressBook.sol

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [x] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hyunsooda** [comment]
A new binding (AddressBook.go) seems absent.

**Comment by ian0371** [comment]
Based on https://scope.klaytn.com/tx/0x1446e71ae430e8bdab36589fe6feb41c9adbe395efb3cfc1ecaf1d1808d2c840?tabId=internalTx, LGTM

**Review by ian0371 — APPROVED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Comment by blukat29** [comment]
Verified with stored code. The value is correct.

```
$ curl -sSL -X POST 'https://public-node-api.klaytnapi.com/v1/cypress' -H 'x-chain-id: 8217' -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"klay_getCode","params":["0x0000000000000000000000000000000000000400", "latest"],"id":1}' \
    | grep -ic 88bb3838aa0a140aCb73EEb3d4B25a8D3aFD58D4
0
$ curl -sSL -X POST 'https://public-node-api.klaytnapi.com/v1/cypress' -H 'x-chain-id: 8217' -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"klay_getCode","params":["0x0000000000000000000000000000000000000400", "latest"],"id":1}' \
    | grep -ic 854CA8508C8BE2bb1f3C244045786410Cb7D5D0a
1
```

**Review by aidan-kwon — COMMENTED** [review]
We need to change `AddressBookBin`, `AddressBookBinRuntime`, and `BaobabAddressBookBin`

**Review by blukat29 — APPROVED** [review]

**Comment by kjhman21** [comment]
I'm closing this issue because it could be better to leave as it is for testing purpose.
Also, we need to take care of this by not directly hard-coding the address value in the contract source code.

**Pull request closed without merging**
