### PR TITLE
Modified to use senderCache when prefetching with Lock unlike #962

### PR DESCRIPTION
**Pull request by KimKyungup**
## Proposed changes
Like #962, this PR can resolve the issue. But the added `lock` can protects a race condition of the uint64 variable.

### Test Result
EN0 : v1.6.1
EN1 : v1.6.2.rc3
image

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [ ] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by ehnuje — DISMISSED** [review]

**Comment by KimKyungup** [comment]
PTAL. :)

**Comment by winnie-byun** [comment]
Could you explain specifically how this modification solves the problem?
To me, it looks like `currentBlockNumber` is only used in `AccountCreationGas` and `SigValidationGas`, which only read `currentBlockNumber`.

**Comment by KimKyungup** [comment]
> Could you explain specifically how this modification solves the problem?
> To me, it looks like `currentBlockNumber` is only used in `AccountCreationGas` and `SigValidationGas`, which only read `currentBlockNumber`.

I added this lock to prohibit a race condition between below logics.
`tx.validatedIntrinsicGas = intrinsicGas + gasFrom`
`tx.validatedIntrinsicGas += gasFeePayer`

But After your comment, I figure out  that the blocknumber can make a race condition with different blocknumber.
We need to find a better way. @winnie-byun @ehnuje

**Review by winnie-byun — APPROVED** [review]

**Comment by KimKyungup** [comment]
PTAL. :)

**Review by ehnuje — APPROVED** [review]

**Review by jeongkyun-oh — APPROVED** [review]

**Pull request merged**
