### PR TITLE
state: added more metrics for StateDB/stateObject operations

### PR DESCRIPTION
**Pull request by ehnuje**
## Proposed changes

- From https://github.com/ethereum/go-ethereum/pull/19316
- Added more metrics to break down block mining/insertion time
- Mining/Insertion details are collected by different metrics
- `state. EnabledExpensive` and `DBConfig. EnableDBPerfMetrics` will be merged into a static flag in the upcoming PR

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by KimKyungup — APPROVED** [review]
Good.
@ehnuje 
How about enable this metrics by default?
Is this change lighter than your last experiment?

**Comment by ehnuje** [comment]
> Good.
> @ehnuje
> How about enable this metrics by default?
> Is this change lighter than your last experiment?

@KimKyungup This should be lighter since it just accumulates the data while block processing and send the data to metrics block by block. These are enabled by default since the default value of the flag is true.

**Comment by KimKyungup** [comment]
> > Good.
> > @ehnuje
> > How about enable this metrics by default?
> > Is this change lighter than your last experiment?
> 
> @KimKyungup This should be lighter since it just accumulates the data while block processing and send the data to metrics block by block. These are enabled by default since the default value of the flag is true.

Got it. Thanks. :)

**Comment by ehnuje** [comment]
@winnie-byun @yoomee1313 @jeongkyun-oh Please take a look.

**Comment by ehnuje** [comment]
@winnie-byun @yoomee1313 Could you please review this change?

**Review by winnie-byun — APPROVED** [review]

**Review by yoomee1313 — APPROVED** [review]

**Pull request merged**
