### PR TITLE
[Master] release/v1.8.0 QA Sign-off

### PR DESCRIPTION
**Pull request by circleci-klaytn**
This PR is automatically created by CI to release a new official version of klaytn.

When this PR is approved by QA team, a new version will be released.

### CODE REVIEW

**Comment by circleci-klaytn** [comment]
<details><summary>Builds ready [fe9b980]</summary><ul><li>Linux: <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kcn-v1.8.0~rc.4-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kpn-v1.8.0~rc.4-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/ken-v1.8.0~rc.4-0-linux-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kscn-v1.8.0~rc.4-0-linux-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kspn-v1.8.0~rc.4-0-linux-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/ksen-v1.8.0~rc.4-0-linux-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kbn-v1.8.0~rc.4-0-linux-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kgen-v1.8.0~rc.4-0-linux-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/homi-v1.8.0~rc.4-0-linux-amd64.tar.gz>homi</a> </li><li>Darwin: <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kcn-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kpn-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/ken-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kscn-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kspn-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/ksen-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kbn-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kgen-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/homi-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>homi</a> </li><li>Baobab-linux: <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kcn-baobab-v1.8.0~rc.4-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kpn-baobab-v1.8.0~rc.4-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/ken-baobab-v1.8.0~rc.4-0-linux-amd64.tar.gz>ken</a> </li><li>Baobab-darwin: <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kcn-baobab-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/kpn-baobab-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.8.0~rc.4/ken-baobab-v1.8.0~rc.4-0-darwin-10.10-amd64.tar.gz>ken</a> </li></ul></details>

**Comment by aidan-kwon** [comment]
All tests are completed in https://github.com/klaytn/klaytn/issues/1146

**Review by aidan-kwon — APPROVED** [review]

**Comment by aidan-kwon** [comment]
Reviewers, please review this PR. 
The coverage test failure is not related to the change of this PR and will be handled soon.

**Review by jeongkyun-oh — APPROVED** [review]

**Comment by aidan-kwon** [comment]
Close this PR because of CircleCI issue. 
I will request the same change with another PR.

**Pull request closed without merging**
