### PR TITLE
database: added fileDB interface and s3FileDB implementation

### PR DESCRIPTION
**Pull request by ehnuje**
## Proposed changes

- This PR introduces `fileDB` interface and one of its implementation `s3FileDB` based on AWS S3.
- `fileDB` inserts an item, which has key and value in byte slice. It inserts the item to somewhere and returns the location of the item. An item can be retrieved with the returned location, URI.
- `s3FileDB` is an implementation of fileDB based on AWS S3. It stores the data to the designated AWS S3 bucket.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ehnuje** [comment]
@KimKyungup @kjhman21 This is for reviewing purpose for now, however, do you think an independent branch is needed for KES development?

**Comment by ehnuje** [comment]
@jeongkyun-oh It seems I can't add you as a reviewer..

**Comment by ehnuje** [comment]
> @KimKyungup @kjhman21 This is for reviewing purpose for now, however, do you think an independent branch is needed for KES development?

Could you please check this comment? @KimKyungup @kjhman21

**Comment by KimKyungup** [comment]
There is another repo. I close this PR. If you need, reopen please.

**Pull request closed without merging**
