### PR TITLE
[Master] release/v1.6.0 QA Sign-off

### PR DESCRIPTION
**Pull request by circleci-klaytn**
This PR is automatically created by CI to release a new official version of klaytn.

When this PR is approved by QA team, a new version will be released.

# v1.6.0 Release Notes

## New Features
- Introduced KES (Klaytn Endpoint System) (#707, #709)
  - Supported shared database and cache
  - KES Fetcher node processes blocks and KES Service node serves APIs with the shared database/cache without its processing
- Added debug.startCollectingTrieStats API which shows a stat of state trie (#740)
- Added debug.getModifiedStorageNodesByNumber API which returns modified trie nodes from the contract sotrage (#742)
- Added logs to show block processing summary (#747)
- Fixed an err in 4byte tracer and Added unigram/bigram/trigram tracers (#752)
- Supported ABIEncoderV2 to pack dynamic array and slice type (#753)
- Supported ABI to unpack tuple type and bytesN arrays (#807, #792, #786)
- Introduced state.trie-cache-save-period option for periodical saving fast cache to filesystem (#828)
- Added debug.StartContractWarmUp(common.Address) API to warm up contract storage trie node (#831)
- Introduced state prefetcher which executes future blocks and future transactions against current state for pre-loading state trie cache (#832, #860)

## Improvements
- Split chain data to send Kafka messages by chain data fetcher (#708, #712)
- Changed metrics.Meter to metrics.Timer (#817)
- Updated default docker image ID (#824)
- Increased FD limit to the maximum value of the process (#827)

## Fixes
- Fixed the path for saving trie node cache (#751)

## Miscellaneous
- Disabled seek compaction for LevelDB (#715)
- Performed code refactoring (#730, #733, #735)
- Updated golang to 1.15.7 version (#875, #871)

### CODE REVIEW

**Comment by circleci-klaytn** [comment]
<details><summary>Builds ready [47d56df]</summary><ul><li>Linux: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kcn-v1.6.0~rc.1-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kpn-v1.6.0~rc.1-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/ken-v1.6.0~rc.1-0-linux-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kscn-v1.6.0~rc.1-0-linux-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kspn-v1.6.0~rc.1-0-linux-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/ksen-v1.6.0~rc.1-0-linux-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kbn-v1.6.0~rc.1-0-linux-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kgen-v1.6.0~rc.1-0-linux-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/homi-v1.6.0~rc.1-0-linux-amd64.tar.gz>homi</a> </li><li>Darwin: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kcn-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kpn-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/ken-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kscn-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kspn-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/ksen-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kbn-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kgen-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/homi-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>homi</a> </li><li>Baobab-linux: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kcn-baobab-v1.6.0~rc.1-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kpn-baobab-v1.6.0~rc.1-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/ken-baobab-v1.6.0~rc.1-0-linux-amd64.tar.gz>ken</a> </li><li>Baobab-darwin: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kcn-baobab-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/kpn-baobab-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.1/ken-baobab-v1.6.0~rc.1-0-darwin-10.10-amd64.tar.gz>ken</a> </li></ul></details>

**Review by ehnuje — DISMISSED** [review]

**Review by KimKyungup — APPROVED** [review]

**Review by winnie-byun — DISMISSED** [review]

**Review by jeongkyun-oh — APPROVED** [review]

**Comment by KimKyungup** [comment]
We need to merge https://github.com/klaytn/klaytn/pull/881.
So I will close this and make another sign-off PR.

**Comment by circleci-klaytn** [comment]
<details><summary>Builds ready [bc397d4]</summary><ul><li>Linux: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kcn-v1.6.0~rc.2-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kpn-v1.6.0~rc.2-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/ken-v1.6.0~rc.2-0-linux-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kscn-v1.6.0~rc.2-0-linux-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kspn-v1.6.0~rc.2-0-linux-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/ksen-v1.6.0~rc.2-0-linux-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kbn-v1.6.0~rc.2-0-linux-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kgen-v1.6.0~rc.2-0-linux-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/homi-v1.6.0~rc.2-0-linux-amd64.tar.gz>homi</a> </li><li>Darwin: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kcn-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kpn-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/ken-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kscn-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kspn-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/ksen-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kbn-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kgen-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/homi-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>homi</a> </li><li>Baobab-linux: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kcn-baobab-v1.6.0~rc.2-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kpn-baobab-v1.6.0~rc.2-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/ken-baobab-v1.6.0~rc.2-0-linux-amd64.tar.gz>ken</a> </li><li>Baobab-darwin: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kcn-baobab-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/kpn-baobab-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.2/ken-baobab-v1.6.0~rc.2-0-darwin-10.10-amd64.tar.gz>ken</a> </li></ul></details>

**Review by winnie-byun — DISMISSED** [review]

**Comment by KimKyungup** [comment]
# Tests
- Sync test
  - Baobab : PASS
  - Cypress : PASS
  - Rolling Update : PASS
# QA bot test
- Reward : PASS
- Governance : PASS
- Service Chain : PASS
- Caver : PASS

**Review by michael-gx — DISMISSED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Review by ehnuje — DISMISSED** [review]

**Comment by circleci-klaytn** [comment]
<details><summary>Builds ready [660aeac]</summary><ul><li>Linux: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kcn-v1.6.0~rc.3-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kpn-v1.6.0~rc.3-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/ken-v1.6.0~rc.3-0-linux-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kscn-v1.6.0~rc.3-0-linux-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kspn-v1.6.0~rc.3-0-linux-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/ksen-v1.6.0~rc.3-0-linux-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kbn-v1.6.0~rc.3-0-linux-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kgen-v1.6.0~rc.3-0-linux-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/homi-v1.6.0~rc.3-0-linux-amd64.tar.gz>homi</a> </li><li>Darwin: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kcn-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kpn-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/ken-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>ken</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kscn-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kscn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kspn-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kspn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/ksen-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>ksen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kbn-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kbn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kgen-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kgen</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/homi-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>homi</a> </li><li>Baobab-linux: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kcn-baobab-v1.6.0~rc.3-0-linux-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kpn-baobab-v1.6.0~rc.3-0-linux-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/ken-baobab-v1.6.0~rc.3-0-linux-amd64.tar.gz>ken</a> </li><li>Baobab-darwin: <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kcn-baobab-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kcn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/kpn-baobab-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>kpn</a> <a href=http://packages.klaytn.net/klaytn/v1.6.0~rc.3/ken-baobab-v1.6.0~rc.3-0-darwin-10.10-amd64.tar.gz>ken</a> </li></ul></details>

**Comment by KimKyungup** [comment]
The added commit (https://github.com/klaytn/klaytn/pull/880/commits/660aeacdb5146f041c2b45ca38b72581b23f91d7) is minor change for log level. So we skip to test it.

**Review by ehnuje — APPROVED** [review]

**Review by yoomee1313 — APPROVED** [review]

**Review by aidan-kwon — APPROVED** [review]

**Review by jeongkyun-oh — APPROVED** [review]

**Comment by KimKyungup** [comment]
Dear reviewer.
We decided to release this as the v1.6.0 release. 
Then the under reviewing PR will be included in the next release v1.6.1.

**Review by KimKyungup — APPROVED** [review]

**Review by michael-gx — APPROVED** [review]

**Pull request merged**
