### PR TITLE
Initial porting StackTrie

### PR DESCRIPTION
**Pull request by hqjang-pepper**
## Proposed changes

- StackTrie is a new feature that improves DeriveSha, which is used in making receipts and transactions.

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn)
- [x] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hqjang-pepper** [comment]
Benchmark test Result

Tested with `100`, `1000`,`2000`,`20000` (key, value) tx data

```
stackTrie
BenchmarkDeriveShaOrig/100test-stackTrie-16         	    5306            217890 ns/op
BenchmarkDeriveShaOrig/1000test-stackTrie-16                 591	   2206139 ns/op
BenchmarkDeriveShaOrig/2000test-stackTrie-16         	     264	   4666449 ns/op
BenchmarkDeriveShaOrig/20000test-stackTrie-16         	      26	   43659012 ns/op

stdTrie
BenchmarkDeriveShaOrig/100test-stdTrie-16         	     4987	    217213 ns/op
BenchmarkDeriveShaOrig/1000test-stdTrie-16         	     426	   2644573 ns/op
BenchmarkDeriveShaOrig/2000test-stdTrie-16         	     195	   5171583 ns/op
BenchmarkDeriveShaOrig/20000test-stdTrie-16         	      20	  61154530 ns/op
```

**Comment by hqjang-pepper** [comment]
Since Klaytn use DeriveShaConcat, not DeriveShaorg,
so StackTrie may not be used. 
For this reason, close this PR until usage needed.

**Comment by kjhman21** [comment]
@hqjang-pepper I don't think this PR should be closed. Why don't you merge this for the future? StackTrie is an optimized trie for incrementally ordered insertion in general.

**Comment by hqjang-pepper** [comment]
Okay, I'll merge this into new branch.
Let's open additional PR if it's needed to merged into dev branch.

**Pull request merged**
